//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSSLWebserviceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eSSLWebserviceReference.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeeResponse> UpdateEmployeeAsync(eSSLWebserviceReference.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployeeEx", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeeExResponse> UpdateEmployeeExAsync(eSSLWebserviceReference.UpdateEmployeeExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployeewithExpiryDates", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeewithExpiryDatesResponse> UpdateEmployeewithExpiryDatesAsync(eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployeePhoto", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeePhotoResponse> UpdateEmployeePhotoAsync(eSSLWebserviceReference.UpdateEmployeePhotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.DeleteEmployeeResponse> DeleteEmployeeAsync(eSSLWebserviceReference.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeeCodesResponse> GetEmployeeCodesAsync(eSSLWebserviceReference.GetEmployeeCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeeDetailsResponse> GetEmployeeDetailsAsync(eSSLWebserviceReference.GetEmployeeDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeePunchLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeePunchLogsResponse> GetEmployeePunchLogsAsync(eSSLWebserviceReference.GetEmployeePunchLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeviceList", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceListResponse> GetDeviceListAsync(eSSLWebserviceReference.GetDeviceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeviceLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceLogsResponse> GetDeviceLogsAsync(eSSLWebserviceReference.GetDeviceLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeviceIllegalLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceIllegalLogsResponse> GetDeviceIllegalLogsAsync(eSSLWebserviceReference.GetDeviceIllegalLogsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest()
        {
        }
        
        public UpdateEmployeeRequest(eSSLWebserviceReference.UpdateEmployeeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeeLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeeRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmployeeVerificationType;
        
        public UpdateEmployeeRequestBody()
        {
        }
        
        public UpdateEmployeeRequestBody(string UserName, string Password, string EmployeeCode, string EmployeeName, string EmployeeLocation, string EmployeeRole, string EmployeeVerificationType)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
            this.EmployeeName = EmployeeName;
            this.EmployeeLocation = EmployeeLocation;
            this.EmployeeRole = EmployeeRole;
            this.EmployeeVerificationType = EmployeeVerificationType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse()
        {
        }
        
        public UpdateEmployeeResponse(eSSLWebserviceReference.UpdateEmployeeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody()
        {
        }
        
        public UpdateEmployeeResponseBody(string UpdateEmployeeResult)
        {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeEx", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeeExRequestBody Body;
        
        public UpdateEmployeeExRequest()
        {
        }
        
        public UpdateEmployeeExRequest(eSSLWebserviceReference.UpdateEmployeeExRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeExRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeeLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeeRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmployeeVerificationType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string EmployeeExpiryFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string EmployeeExpiryTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EmployeeCardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string EmployeePhoto;
        
        public UpdateEmployeeExRequestBody()
        {
        }
        
        public UpdateEmployeeExRequestBody(string UserName, string Password, string EmployeeCode, string EmployeeName, string EmployeeLocation, string EmployeeRole, string EmployeeVerificationType, string EmployeeExpiryFrom, string EmployeeExpiryTo, string EmployeeCardNumber, string EmployeePhoto)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
            this.EmployeeName = EmployeeName;
            this.EmployeeLocation = EmployeeLocation;
            this.EmployeeRole = EmployeeRole;
            this.EmployeeVerificationType = EmployeeVerificationType;
            this.EmployeeExpiryFrom = EmployeeExpiryFrom;
            this.EmployeeExpiryTo = EmployeeExpiryTo;
            this.EmployeeCardNumber = EmployeeCardNumber;
            this.EmployeePhoto = EmployeePhoto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeExResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeeExResponseBody Body;
        
        public UpdateEmployeeExResponse()
        {
        }
        
        public UpdateEmployeeExResponse(eSSLWebserviceReference.UpdateEmployeeExResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeExResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeeExResult;
        
        public UpdateEmployeeExResponseBody()
        {
        }
        
        public UpdateEmployeeExResponseBody(string UpdateEmployeeExResult)
        {
            this.UpdateEmployeeExResult = UpdateEmployeeExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeewithExpiryDatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeewithExpiryDates", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequestBody Body;
        
        public UpdateEmployeewithExpiryDatesRequest()
        {
        }
        
        public UpdateEmployeewithExpiryDatesRequest(eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeewithExpiryDatesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EmployeeLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmployeeRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EmployeeVerificationType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string EmployeeExpiryFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string EmployeeExpiryTo;
        
        public UpdateEmployeewithExpiryDatesRequestBody()
        {
        }
        
        public UpdateEmployeewithExpiryDatesRequestBody(string UserName, string Password, string EmployeeCode, string EmployeeName, string EmployeeLocation, string EmployeeRole, string EmployeeVerificationType, string EmployeeExpiryFrom, string EmployeeExpiryTo)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
            this.EmployeeName = EmployeeName;
            this.EmployeeLocation = EmployeeLocation;
            this.EmployeeRole = EmployeeRole;
            this.EmployeeVerificationType = EmployeeVerificationType;
            this.EmployeeExpiryFrom = EmployeeExpiryFrom;
            this.EmployeeExpiryTo = EmployeeExpiryTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeewithExpiryDatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeewithExpiryDatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeewithExpiryDatesResponseBody Body;
        
        public UpdateEmployeewithExpiryDatesResponse()
        {
        }
        
        public UpdateEmployeewithExpiryDatesResponse(eSSLWebserviceReference.UpdateEmployeewithExpiryDatesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeewithExpiryDatesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeewithExpiryDatesResult;
        
        public UpdateEmployeewithExpiryDatesResponseBody()
        {
        }
        
        public UpdateEmployeewithExpiryDatesResponseBody(string UpdateEmployeewithExpiryDatesResult)
        {
            this.UpdateEmployeewithExpiryDatesResult = UpdateEmployeewithExpiryDatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeePhotoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeePhoto", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeePhotoRequestBody Body;
        
        public UpdateEmployeePhotoRequest()
        {
        }
        
        public UpdateEmployeePhotoRequest(eSSLWebserviceReference.UpdateEmployeePhotoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeePhotoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmployeePhoto;
        
        public UpdateEmployeePhotoRequestBody()
        {
        }
        
        public UpdateEmployeePhotoRequestBody(string UserName, string Password, string EmployeeCode, string EmployeePhoto)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
            this.EmployeePhoto = EmployeePhoto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeePhotoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeePhotoResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.UpdateEmployeePhotoResponseBody Body;
        
        public UpdateEmployeePhotoResponse()
        {
        }
        
        public UpdateEmployeePhotoResponse(eSSLWebserviceReference.UpdateEmployeePhotoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeePhotoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeePhotoResult;
        
        public UpdateEmployeePhotoResponseBody()
        {
        }
        
        public UpdateEmployeePhotoResponseBody(string UpdateEmployeePhotoResult)
        {
            this.UpdateEmployeePhotoResult = UpdateEmployeePhotoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest()
        {
        }
        
        public DeleteEmployeeRequest(eSSLWebserviceReference.DeleteEmployeeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        public DeleteEmployeeRequestBody()
        {
        }
        
        public DeleteEmployeeRequestBody(string UserName, string Password, string EmployeeCode)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse()
        {
        }
        
        public DeleteEmployeeResponse(eSSLWebserviceReference.DeleteEmployeeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEmployeeResult;
        
        public DeleteEmployeeResponseBody()
        {
        }
        
        public DeleteEmployeeResponseBody(string DeleteEmployeeResult)
        {
            this.DeleteEmployeeResult = DeleteEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeCodesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeCodes", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetEmployeeCodesRequestBody Body;
        
        public GetEmployeeCodesRequest()
        {
        }
        
        public GetEmployeeCodesRequest(eSSLWebserviceReference.GetEmployeeCodesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeCodesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeLocation;
        
        public GetEmployeeCodesRequestBody()
        {
        }
        
        public GetEmployeeCodesRequestBody(string UserName, string Password, string EmployeeLocation)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeLocation = EmployeeLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeCodesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeCodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetEmployeeCodesResponseBody Body;
        
        public GetEmployeeCodesResponse()
        {
        }
        
        public GetEmployeeCodesResponse(eSSLWebserviceReference.GetEmployeeCodesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeCodesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmployeeCodesResult;
        
        public GetEmployeeCodesResponseBody()
        {
        }
        
        public GetEmployeeCodesResponseBody(string GetEmployeeCodesResult)
        {
            this.GetEmployeeCodesResult = GetEmployeeCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDetails", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetEmployeeDetailsRequestBody Body;
        
        public GetEmployeeDetailsRequest()
        {
        }
        
        public GetEmployeeDetailsRequest(eSSLWebserviceReference.GetEmployeeDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        public GetEmployeeDetailsRequestBody()
        {
        }
        
        public GetEmployeeDetailsRequestBody(string UserName, string Password, string EmployeeCode)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetEmployeeDetailsResponseBody Body;
        
        public GetEmployeeDetailsResponse()
        {
        }
        
        public GetEmployeeDetailsResponse(eSSLWebserviceReference.GetEmployeeDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmployeeDetailsResult;
        
        public GetEmployeeDetailsResponseBody()
        {
        }
        
        public GetEmployeeDetailsResponseBody(string GetEmployeeDetailsResult)
        {
            this.GetEmployeeDetailsResult = GetEmployeeDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeePunchLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeePunchLogs", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetEmployeePunchLogsRequestBody Body;
        
        public GetEmployeePunchLogsRequest()
        {
        }
        
        public GetEmployeePunchLogsRequest(eSSLWebserviceReference.GetEmployeePunchLogsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeePunchLogsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmployeeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AttendanceDate;
        
        public GetEmployeePunchLogsRequestBody()
        {
        }
        
        public GetEmployeePunchLogsRequestBody(string UserName, string Password, string EmployeeCode, string AttendanceDate)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.EmployeeCode = EmployeeCode;
            this.AttendanceDate = AttendanceDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeePunchLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeePunchLogsResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetEmployeePunchLogsResponseBody Body;
        
        public GetEmployeePunchLogsResponse()
        {
        }
        
        public GetEmployeePunchLogsResponse(eSSLWebserviceReference.GetEmployeePunchLogsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeePunchLogsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmployeePunchLogsResult;
        
        public GetEmployeePunchLogsResponseBody()
        {
        }
        
        public GetEmployeePunchLogsResponseBody(string GetEmployeePunchLogsResult)
        {
            this.GetEmployeePunchLogsResult = GetEmployeePunchLogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceList", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetDeviceListRequestBody Body;
        
        public GetDeviceListRequest()
        {
        }
        
        public GetDeviceListRequest(eSSLWebserviceReference.GetDeviceListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location;
        
        public GetDeviceListRequestBody()
        {
        }
        
        public GetDeviceListRequestBody(string UserName, string Password, string Location)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.Location = Location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceListResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetDeviceListResponseBody Body;
        
        public GetDeviceListResponse()
        {
        }
        
        public GetDeviceListResponse(eSSLWebserviceReference.GetDeviceListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceListResult;
        
        public GetDeviceListResponseBody()
        {
        }
        
        public GetDeviceListResponseBody(string GetDeviceListResult)
        {
            this.GetDeviceListResult = GetDeviceListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceLogs", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetDeviceLogsRequestBody Body;
        
        public GetDeviceLogsRequest()
        {
        }
        
        public GetDeviceLogsRequest(eSSLWebserviceReference.GetDeviceLogsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceLogsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LogDate;
        
        public GetDeviceLogsRequestBody()
        {
        }
        
        public GetDeviceLogsRequestBody(string UserName, string Password, string Location, string LogDate)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.Location = Location;
            this.LogDate = LogDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceLogsResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetDeviceLogsResponseBody Body;
        
        public GetDeviceLogsResponse()
        {
        }
        
        public GetDeviceLogsResponse(eSSLWebserviceReference.GetDeviceLogsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceLogsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceLogsResult;
        
        public GetDeviceLogsResponseBody()
        {
        }
        
        public GetDeviceLogsResponseBody(string GetDeviceLogsResult)
        {
            this.GetDeviceLogsResult = GetDeviceLogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceIllegalLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceIllegalLogs", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetDeviceIllegalLogsRequestBody Body;
        
        public GetDeviceIllegalLogsRequest()
        {
        }
        
        public GetDeviceIllegalLogsRequest(eSSLWebserviceReference.GetDeviceIllegalLogsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceIllegalLogsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LogDate;
        
        public GetDeviceIllegalLogsRequestBody()
        {
        }
        
        public GetDeviceIllegalLogsRequestBody(string UserName, string Password, string Location, string LogDate)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.Location = Location;
            this.LogDate = LogDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceIllegalLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceIllegalLogsResponse", Namespace="http://tempuri.org/", Order=0)]
        public eSSLWebserviceReference.GetDeviceIllegalLogsResponseBody Body;
        
        public GetDeviceIllegalLogsResponse()
        {
        }
        
        public GetDeviceIllegalLogsResponse(eSSLWebserviceReference.GetDeviceIllegalLogsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceIllegalLogsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceIllegalLogsResult;
        
        public GetDeviceIllegalLogsResponseBody()
        {
        }
        
        public GetDeviceIllegalLogsResponseBody(string GetDeviceIllegalLogsResult)
        {
            this.GetDeviceIllegalLogsResult = GetDeviceIllegalLogsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebServiceSoapChannel : eSSLWebserviceReference.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<eSSLWebserviceReference.WebServiceSoap>, eSSLWebserviceReference.WebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeeResponse> eSSLWebserviceReference.WebServiceSoap.UpdateEmployeeAsync(eSSLWebserviceReference.UpdateEmployeeRequest request)
        {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeeResponse> UpdateEmployeeAsync(string UserName, string Password, string EmployeeCode, string EmployeeName, string EmployeeLocation, string EmployeeRole, string EmployeeVerificationType)
        {
            eSSLWebserviceReference.UpdateEmployeeRequest inValue = new eSSLWebserviceReference.UpdateEmployeeRequest();
            inValue.Body = new eSSLWebserviceReference.UpdateEmployeeRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.EmployeeName = EmployeeName;
            inValue.Body.EmployeeLocation = EmployeeLocation;
            inValue.Body.EmployeeRole = EmployeeRole;
            inValue.Body.EmployeeVerificationType = EmployeeVerificationType;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeeExResponse> eSSLWebserviceReference.WebServiceSoap.UpdateEmployeeExAsync(eSSLWebserviceReference.UpdateEmployeeExRequest request)
        {
            return base.Channel.UpdateEmployeeExAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeeExResponse> UpdateEmployeeExAsync(string UserName, string Password, string EmployeeCode, string EmployeeName, string EmployeeLocation, string EmployeeRole, string EmployeeVerificationType, string EmployeeExpiryFrom, string EmployeeExpiryTo, string EmployeeCardNumber, string EmployeePhoto)
        {
            eSSLWebserviceReference.UpdateEmployeeExRequest inValue = new eSSLWebserviceReference.UpdateEmployeeExRequest();
            inValue.Body = new eSSLWebserviceReference.UpdateEmployeeExRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.EmployeeName = EmployeeName;
            inValue.Body.EmployeeLocation = EmployeeLocation;
            inValue.Body.EmployeeRole = EmployeeRole;
            inValue.Body.EmployeeVerificationType = EmployeeVerificationType;
            inValue.Body.EmployeeExpiryFrom = EmployeeExpiryFrom;
            inValue.Body.EmployeeExpiryTo = EmployeeExpiryTo;
            inValue.Body.EmployeeCardNumber = EmployeeCardNumber;
            inValue.Body.EmployeePhoto = EmployeePhoto;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).UpdateEmployeeExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeewithExpiryDatesResponse> eSSLWebserviceReference.WebServiceSoap.UpdateEmployeewithExpiryDatesAsync(eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequest request)
        {
            return base.Channel.UpdateEmployeewithExpiryDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeewithExpiryDatesResponse> UpdateEmployeewithExpiryDatesAsync(string UserName, string Password, string EmployeeCode, string EmployeeName, string EmployeeLocation, string EmployeeRole, string EmployeeVerificationType, string EmployeeExpiryFrom, string EmployeeExpiryTo)
        {
            eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequest inValue = new eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequest();
            inValue.Body = new eSSLWebserviceReference.UpdateEmployeewithExpiryDatesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.EmployeeName = EmployeeName;
            inValue.Body.EmployeeLocation = EmployeeLocation;
            inValue.Body.EmployeeRole = EmployeeRole;
            inValue.Body.EmployeeVerificationType = EmployeeVerificationType;
            inValue.Body.EmployeeExpiryFrom = EmployeeExpiryFrom;
            inValue.Body.EmployeeExpiryTo = EmployeeExpiryTo;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).UpdateEmployeewithExpiryDatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeePhotoResponse> eSSLWebserviceReference.WebServiceSoap.UpdateEmployeePhotoAsync(eSSLWebserviceReference.UpdateEmployeePhotoRequest request)
        {
            return base.Channel.UpdateEmployeePhotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.UpdateEmployeePhotoResponse> UpdateEmployeePhotoAsync(string UserName, string Password, string EmployeeCode, string EmployeePhoto)
        {
            eSSLWebserviceReference.UpdateEmployeePhotoRequest inValue = new eSSLWebserviceReference.UpdateEmployeePhotoRequest();
            inValue.Body = new eSSLWebserviceReference.UpdateEmployeePhotoRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.EmployeePhoto = EmployeePhoto;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).UpdateEmployeePhotoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.DeleteEmployeeResponse> eSSLWebserviceReference.WebServiceSoap.DeleteEmployeeAsync(eSSLWebserviceReference.DeleteEmployeeRequest request)
        {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.DeleteEmployeeResponse> DeleteEmployeeAsync(string UserName, string Password, string EmployeeCode)
        {
            eSSLWebserviceReference.DeleteEmployeeRequest inValue = new eSSLWebserviceReference.DeleteEmployeeRequest();
            inValue.Body = new eSSLWebserviceReference.DeleteEmployeeRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).DeleteEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeeCodesResponse> eSSLWebserviceReference.WebServiceSoap.GetEmployeeCodesAsync(eSSLWebserviceReference.GetEmployeeCodesRequest request)
        {
            return base.Channel.GetEmployeeCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeeCodesResponse> GetEmployeeCodesAsync(string UserName, string Password, string EmployeeLocation)
        {
            eSSLWebserviceReference.GetEmployeeCodesRequest inValue = new eSSLWebserviceReference.GetEmployeeCodesRequest();
            inValue.Body = new eSSLWebserviceReference.GetEmployeeCodesRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeLocation = EmployeeLocation;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).GetEmployeeCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeeDetailsResponse> eSSLWebserviceReference.WebServiceSoap.GetEmployeeDetailsAsync(eSSLWebserviceReference.GetEmployeeDetailsRequest request)
        {
            return base.Channel.GetEmployeeDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeeDetailsResponse> GetEmployeeDetailsAsync(string UserName, string Password, string EmployeeCode)
        {
            eSSLWebserviceReference.GetEmployeeDetailsRequest inValue = new eSSLWebserviceReference.GetEmployeeDetailsRequest();
            inValue.Body = new eSSLWebserviceReference.GetEmployeeDetailsRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).GetEmployeeDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeePunchLogsResponse> eSSLWebserviceReference.WebServiceSoap.GetEmployeePunchLogsAsync(eSSLWebserviceReference.GetEmployeePunchLogsRequest request)
        {
            return base.Channel.GetEmployeePunchLogsAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.GetEmployeePunchLogsResponse> GetEmployeePunchLogsAsync(string UserName, string Password, string EmployeeCode, string AttendanceDate)
        {
            eSSLWebserviceReference.GetEmployeePunchLogsRequest inValue = new eSSLWebserviceReference.GetEmployeePunchLogsRequest();
            inValue.Body = new eSSLWebserviceReference.GetEmployeePunchLogsRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.EmployeeCode = EmployeeCode;
            inValue.Body.AttendanceDate = AttendanceDate;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).GetEmployeePunchLogsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceListResponse> eSSLWebserviceReference.WebServiceSoap.GetDeviceListAsync(eSSLWebserviceReference.GetDeviceListRequest request)
        {
            return base.Channel.GetDeviceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceListResponse> GetDeviceListAsync(string UserName, string Password, string Location)
        {
            eSSLWebserviceReference.GetDeviceListRequest inValue = new eSSLWebserviceReference.GetDeviceListRequest();
            inValue.Body = new eSSLWebserviceReference.GetDeviceListRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.Location = Location;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).GetDeviceListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceLogsResponse> eSSLWebserviceReference.WebServiceSoap.GetDeviceLogsAsync(eSSLWebserviceReference.GetDeviceLogsRequest request)
        {
            return base.Channel.GetDeviceLogsAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceLogsResponse> GetDeviceLogsAsync(string UserName, string Password, string Location, string LogDate)
        {
            eSSLWebserviceReference.GetDeviceLogsRequest inValue = new eSSLWebserviceReference.GetDeviceLogsRequest();
            inValue.Body = new eSSLWebserviceReference.GetDeviceLogsRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.Location = Location;
            inValue.Body.LogDate = LogDate;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).GetDeviceLogsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceIllegalLogsResponse> eSSLWebserviceReference.WebServiceSoap.GetDeviceIllegalLogsAsync(eSSLWebserviceReference.GetDeviceIllegalLogsRequest request)
        {
            return base.Channel.GetDeviceIllegalLogsAsync(request);
        }
        
        public System.Threading.Tasks.Task<eSSLWebserviceReference.GetDeviceIllegalLogsResponse> GetDeviceIllegalLogsAsync(string UserName, string Password, string Location, string LogDate)
        {
            eSSLWebserviceReference.GetDeviceIllegalLogsRequest inValue = new eSSLWebserviceReference.GetDeviceIllegalLogsRequest();
            inValue.Body = new eSSLWebserviceReference.GetDeviceIllegalLogsRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.Location = Location;
            inValue.Body.LogDate = LogDate;
            return ((eSSLWebserviceReference.WebServiceSoap)(this)).GetDeviceIllegalLogsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ebioservernew.esslsecurity.com:99/webservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ebioservernew.esslsecurity.com:99/webservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
            
            WebServiceSoap12,
        }
    }
}
